export default function Terms() {
  return (
    <>
      <style jsx>{pageStyles}</style>
      <div className="page">
        <div className="content">
          <div className="nav">
            <a href="/" className="wordmark">RehabMetrics <span className="wordmark-iq">IQ</span></a>
          </div>

          <h1 className="title">Terms of Service</h1>
          <p className="meta">Last updated: April 2026</p>

          <p className="intro">
            Please read these Terms of Service carefully before using RehabMetrics IQ. By creating an account or
            using the service, you agree to be bound by these terms.
          </p>

          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using RehabMetrics IQ, you agree to these Terms of Service and our{' '}
            <a href="/privacy">Privacy Policy</a>. If you do not agree, do not use the service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            RehabMetrics IQ is a clinical documentation tool that helps physiotherapists and rehabilitation
            clinicians record, score, and interpret standardised outcome measures. The service is provided
            on a subscription basis following a 14-day free trial.
          </p>

          <h2>3. Eligibility</h2>
          <p>
            RehabMetrics IQ is intended for use by qualified healthcare professionals only. By creating an account,
            you confirm that you are a registered or licensed clinician in your jurisdiction and that you will use
            the service in accordance with applicable professional and legal standards.
          </p>

          <h2>4. Clinical Disclaimer</h2>
          <p>
            RehabMetrics IQ is a documentation and scoring assistance tool. It is <strong>not a medical device</strong>,
            does not provide diagnoses, and does not constitute clinical advice. All clinical decisions are the sole
            responsibility of the treating clinician.
          </p>
          <p>
            Scores and interpretations generated by RehabMetrics IQ are derived from published normative data and
            should be interpreted in the context of the individual patient. RehabMetrics IQ accepts no liability
            for clinical decisions made on the basis of information produced by the service.
          </p>

          <h2>5. Patient Data and Privacy</h2>
          <p>
            You are responsible for ensuring that your use of the service complies with applicable privacy laws
            in your jurisdiction. We recommend using patient initials rather than full names, and not entering
            Medicare numbers or other government identifiers. See our <a href="/privacy">Privacy Policy</a> for
            details on how we handle data.
          </p>

          <h2>6. Trial and Subscription</h2>
          <ul>
            <li>New accounts receive a 14-day free trial with full access to all features.</li>
            <li>No credit card is required to start a trial.</li>
            <li>After the trial period, continued access requires a paid subscription.</li>
            <li>Subscription fees are billed monthly or annually as selected at checkout.</li>
            <li>You may cancel your subscription at any time. Access continues until the end of the billing period.</li>
          </ul>

          <h2>7. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the service for any unlawful purpose.</li>
            <li>Share your account credentials with others.</li>
            <li>Attempt to reverse-engineer, copy, or resell the service.</li>
            <li>Upload content that is false, misleading, or violates third-party rights.</li>
          </ul>

          <h2>8. Intellectual Property</h2>
          <p>
            All content, design, and software comprising RehabMetrics IQ is the property of RehabMetrics and
            is protected by copyright. Clinical outcome measure scoring algorithms are derived from publicly
            available published literature and referenced accordingly.
          </p>

          <h2>9. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, RehabMetrics shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages arising from your use of the service, including any
            clinical outcomes or patient care decisions.
          </p>
          <p>
            Our total liability to you in any circumstances shall not exceed the amount you paid for the service
            in the three months preceding the claim.
          </p>

          <h2>10. Changes to These Terms</h2>
          <p>
            We may update these terms from time to time. We will notify you by email of material changes.
            Continued use of the service after changes constitutes acceptance of the updated terms.
          </p>

          <h2>11. Governing Law</h2>
          <p>
            These terms are governed by the laws of Victoria, Australia. Any disputes shall be subject to the
            exclusive jurisdiction of the courts of Victoria.
          </p>

          <h2>12. Contact</h2>
          <p>
            For questions about these terms, contact us at{' '}
            <a href="mailto:Support@RehabMetricsIQ.com">Support@RehabMetricsIQ.com</a>.
          </p>

          <div className="footer-links">
            <a href="/privacy">Privacy Policy</a>
            <a href="/data-deletion">Data Deletion</a>
            <a href="/">Back to home</a>
          </div>
        </div>
      </div>
    </>
  )
}

const pageStyles = `
  * { box-sizing: border-box; margin: 0; padding: 0; }

  :root {
    --color-primary:      #236499;
    --color-ink:          #1F2933;
    --color-muted:        #5F6B7A;
    --color-subtle:       #8A96A3;
    --color-surface:      #FFFFFF;
    --color-surface-soft: #F7FAFC;
    --color-border:       #D8E2EC;
  }

  body { font-family: 'Inter', sans-serif; background: var(--color-surface-soft); }

  .page { min-height: 100vh; padding: 48px 24px 80px; }

  .content {
    max-width: 720px;
    margin: 0 auto;
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: 12px;
    padding: 48px 56px;
  }

  .nav { margin-bottom: 40px; }

  .wordmark {
    font-family: 'Source Serif 4', serif;
    font-size: 18px;
    font-weight: 600;
    color: var(--color-primary);
    text-decoration: none;
  }

  .wordmark-iq { font-style: italic; font-weight: 300; }

  .title {
    font-family: 'Source Serif 4', serif;
    font-size: 32px;
    font-weight: 600;
    color: var(--color-ink);
    line-height: 1.2;
    margin-bottom: 8px;
  }

  .meta {
    font-size: 13px;
    color: var(--color-subtle);
    margin-bottom: 32px;
  }

  .intro {
    font-size: 16px;
    color: var(--color-muted);
    line-height: 1.7;
    margin-bottom: 40px;
    padding-bottom: 32px;
    border-bottom: 1px solid var(--color-border);
  }

  h2 {
    font-family: 'Source Serif 4', serif;
    font-size: 20px;
    font-weight: 600;
    color: var(--color-ink);
    margin-top: 36px;
    margin-bottom: 12px;
  }

  p {
    font-size: 15px;
    color: var(--color-muted);
    line-height: 1.7;
    margin-bottom: 14px;
  }

  ul { margin: 0 0 14px 20px; }

  li {
    font-size: 15px;
    color: var(--color-muted);
    line-height: 1.7;
    margin-bottom: 6px;
  }

  strong { color: var(--color-ink); font-weight: 500; }

  a { color: var(--color-primary); text-decoration: none; }
  a:hover { text-decoration: underline; }

  .footer-links {
    display: flex;
    gap: 24px;
    margin-top: 48px;
    padding-top: 24px;
    border-top: 1px solid var(--color-border);
    font-size: 13px;
  }

  @media (max-width: 640px) {
    .content { padding: 32px 24px; }
    .title { font-size: 26px; }
    .footer-links { flex-direction: column; gap: 12px; }
  }
`
